modLoader = "javafml"
loaderVersion = "[${loader_version},)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${version}"
    displayName = "${mod_name}"
    authors = "Lost Myself"
    description = "${mod_description}"
    logoFile = "logo.png"
    displayURL = "${mod_url}"
    credits="Thank you to all those who have made any contributions to this mod"

[[mixins]]
    config = "${mod_id}.mixins.json"
[[accessTransformers]]
    file = "META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "[${neo_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies."${mod_id}"]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "mekanism"
    type = "required"
    versionRange = "[10.7.17]"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "evolvedmekanism"
    type = "optional"
    ordering = "AFTER"
    side = "BOTH"
